GEMINI_API_KEY = "AIzaSyDRGSp9zXaee5--pRTv968pweQL60ViLMs"
SERPER_API_KEY = "f25564a962d288eedc1a2eda7b635b9a9f3e5c12"

# MongoDB Atlas es opcional.
# Si todavía no tienes MongoDB, déjalo vacío.
MONGO_URI = "mongodb+srv://aauroraaboreal_db_user:!Duquecito2021@cluster0.ksh6tj7.mongodb.net/"
MONGO_DB = "sweetbudget"
MONGO_COLLECTION = "busquedas_raw"

[postgres]
USER = "postgres.nrtgdkhlyueerektkofu"
PASSWORD = "!Duquecito2021"
HOST = "aws-1-us-east-1.pooler.supabase.com"
PORT = "6543"
DBNAME = "postgres"